# Generated by Django 3.2.4 on 2022-05-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_name',
            field=models.CharField(default='My Wallet', max_length=100),
        ),
    ]
