# Generated by Django 3.2.4 on 2022-05-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_wallet_wallet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(),
        ),
    ]
